another_vkh/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'car_histories#index'
  resources :users do
    member do
      put 'update_password'
      get 'change_password'
    end
  end

  resources :cars do
    member do
      post 'add_more_detail'
    end
  end
  resources :spare_parts
  resources :spare_part_types
  resources :car_histories do
    member do
      post 'print'
    end
  end
  resources :car_repairing_quotes
  resources :alerts
  resources :historical_reports do 
    member do
      get 'quote'
    end
  end

end

another_vkh/app/models/car.rb
class Car < ActiveRecord::Base
	has_many :sell_reports
	has_many :car_histories
end

another_vkh/app/models/car_history.rb
class CarHistory < ActiveRecord::Base
	belongs_to :car
end

another_vkh/app/models/car_history_spare_part.rb
class CarHistorySparePart < ActiveRecord::Base
end

another_vkh/app/models/car_repairing_quote.rb
class CarRepairingQuote < ActiveRecord::Base
	belongs_to :car_repairing_quote_status
end

another_vkh/app/models/car_repairing_quote_status.rb
class CarRepairingQuoteStatus < ActiveRecord::Base
	has_many :car_repairing_quotes	
end

another_vkh/app/models/car_type.rb
class CarType < ActiveRecord::Base
end

another_vkh/app/models/sell_report.rb
class SellReport < ActiveRecord::Base
	belongs_to :car
	belongs_to :spare_part
end

another_vkh/app/models/spare_part.rb
class SparePart < ActiveRecord::Base
	belongs_to	:spare_part_type
	has_many :sell_reports
end

another_vkh/app/models/spare_part_type.rb
class SparePartType < ActiveRecord::Base
	has_many :spare_parts
end

another_vkh/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

another_vkh/app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
	def index
		@alerts = SparePart.where("amount_in_stock <= ?", 20)
	end
end

another_vkh/app/controllers/cars_controller.rb
class CarsController < ApplicationController

	def index
		@cars = Car.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@car = Car.new

	end

	def create
		@car = Car.new(car_params)
	  if @car.save
	    redirect_to :action => :index
	  else
	    render 'new'
	  end
	end

	def edit
		@car = Car.find(params[:id])
	end

	def update
		@car = Car.find(params[:id])
		@car.update_attributes(car_params)
		if @car.save
	    redirect_to :action => :index
	  else
	    render 'edit'
	  end
	end

	def destroy
		@car = Car.find(params[:id])
		@car.destroy
		redirect_to :action => :index
		flash.notice = "Car #{@car.plate_number} has been deleted"
	end

	private

  def car_params
    params.require(:car).permit(:plate_number, :name)
  end
	
end

another_vkh/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

another_vkh/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index

	end

	def new

	end

	def create

	end

	def edit

	end

	def update

	end

	def destroy

	end

	def change_password
    @user = current_user
  end
end

another_vkh/app/helpers/alert_helper.rb
module AlertHelper
end

another_vkh/app/helpers/alerts_controller_helper.rb
module AlertsControllerHelper
end

another_vkh/app/helpers/application_helper.rb
module ApplicationHelper
	def section_active(action)
  	return (params[:controller] == action)? "active": ""
  end
end

another_vkh/app/helpers/car_histories_helper.rb
module CarHistoriesHelper
end

another_vkh/app/helpers/cars_helper.rb
module CarsHelper
end

another_vkh/app/helpers/historical_reports_helper.rb
module HistoricalReportsHelper
end

another_vkh/app/helpers/home_helper.rb
module HomeHelper
end

another_vkh/app/helpers/spare_part_types_helper.rb
module SparePartTypesHelper
end

another_vkh/app/helpers/spare_parts_helper.rb
module SparePartsHelper
end

another_vkh/app/helpers/users_helper.rb
module UsersHelper
end

another_vkh/app/views/cars/_form.html.erb
<%= bootstrap_form_for(@car, layout: :horizontal ,label_col: "col-sm-2", control_col: "col-sm-3") do |f| %>
  <%= f.text_field :plate_number, :label => "ផ្លាកលេខឡាន" %>
  <%= f.text_field :name, :label => "ប្រភេទ" %>
  <%= f.form_group do %>
    <%= f.submit "រក្សាទុក" %>
  <% end %>
<% end %>

another_vkh/app/views/cars/edit.html.erb
<div id="wrapper">
	<h1 align="center">កែឈ្មោះឡាន</h1>
	<%= render partial: 'cars/form' %>
</div>

another_vkh/app/views/cars/index.html.erb
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-6">
		<div class="nav">
		<div class="navbar-nav navbar-left" style="margin-bottom: 10px;">
			<input type="text" class="form-control" placeholder="Search ..." aria-describedby="sizing-addon1">
		</div>
	  <div class="navbar-nav navbar-right" style="margin-right: 0px;">
	  	<%= button_to "បង្កើតឡានថ្មី", new_car_path, :class => "btn btn-default", :method => "get" %>
	  </div>
  	</div>

	  <div class="panel panel-default">
			<table class="table table-striped table-hover">
				<th style="width: 40%"> ផ្លាកលេខ </th>
				<th style="width: 40%"> ប្រភេទឡាន </th>
				<th style="width: 20%"> </th>

				<% @cars.each do |car| %>
					<tr>
						<td> <%= car.plate_number %> </td>
						<td> <%= car.name %> </td>
						<td>
							<div>
								<span style = "margin-right: 10px;">
									<%= link_to "", edit_car_path(car), class: "glyphicon glyphicon-pencil" %>
								</span>
								<span style = "margin-right: 10px;">
									<%= link_to "", car_path(car), method: :delete, data: {confirm: "Are you sure want to delete this car?"}, class: "glyphicon glyphicon-trash" %>
								</span>
								<span style = "margin-right: 5px;">
									<%= link_to "", cars_path, class: "glyphicon glyphicon-zoom-in" %>
								</span>
							</div>
						</td>
					</tr>
				<% end %>	
			</table>
		</div>
		<div style="margin-top: -25px;">
			<%= will_paginate @cars, renderer: BootstrapPagination::Rails %>
		</div>
	</div>
</div>

another_vkh/app/views/cars/new.html.erb
<div id="wrapper">
  <div class="user-action">
    <h1 align="center">កត់ឈ្មោះឡានថ្មី</h1>
    <%= render partial: 'cars/form' %>
  </div>
</div>