another_vkh/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'car_histories#index'
  resources :users do
    member do
      put 'update_password'
      get 'change_password'
    end
  end

  resources :cars do
    member do
      post 'add_more_detail'
    end
  end
  resources :spare_parts
  resources :spare_part_types
  resources :car_histories do
    member do
      post 'print'
    end
  end
  resources :car_repairing_quotes
  resources :alerts
  resources :historical_reports do 
    member do
      get 'quote'
    end
  end

end

another_vkh/app/models/car.rb
class Car < ActiveRecord::Base
	has_many :sell_reports
	has_many :car_histories
end

another_vkh/app/models/car_history.rb
class CarHistory < ActiveRecord::Base
	belongs_to :car
end

another_vkh/app/models/car_history_spare_part.rb
class CarHistorySparePart < ActiveRecord::Base
end

another_vkh/app/models/car_repairing_quote.rb
class CarRepairingQuote < ActiveRecord::Base
	belongs_to :car_repairing_quote_status
end

another_vkh/app/models/car_type.rb
class CarType < ActiveRecord::Base
end

another_vkh/app/models/sell_report.rb
class SellReport < ActiveRecord::Base
	belongs_to :car
	belongs_to :spare_part
end

another_vkh/app/models/spare_part.rb
class SparePart < ActiveRecord::Base
	belongs_to	:spare_part_type
	has_many :sell_reports
end

another_vkh/app/models/spare_part_type.rb
class SparePartType < ActiveRecord::Base
	has_many :spare_parts
end

another_vkh/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

another_vkh/app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
	def index
		@alerts = SparePart.where("amount_in_stock <= ?", 20)
	end
end

another_vkh/app/controllers/cars_controller.rb
class CarsController < ApplicationController

	def index
		@cars = Car.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@car = Car.new

	end

	def create
		@car = Car.new(car_params)
	  if @car.save
	    redirect_to :action => :index
	  else
	    render 'new'
	  end
	end

	def edit
		@car = Car.find(params[:id])
	end

	def update
		@car = Car.find(params[:id])
		@car.update_attributes(car_params)
		if @car.save
	    redirect_to :action => :index
	  else
	    render 'edit'
	  end
	end

	def destroy
		@car = Car.find(params[:id])
		@car.destroy
		redirect_to :action => :index
		flash.notice = "Car #{@car.plate_number} has been deleted"
	end

	private

  def car_params
    params.require(:car).permit(:plate_number, :name)
  end
	
end

another_vkh/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

another_vkh/app/controllers/spare_part_types_controller.rb
class SparePartTypesController < ApplicationController
	def index
		if params[:search]
			@spare_part_types = SparePartType.where("name like ?", "%#{params[:search]}%").paginate(:page => params[:page], :per_page => 10)
		else
			@spare_part_types = SparePartType.paginate(:page => params[:page], :per_page => 10)
		end
	end

	def new
		@spare_part_type = SparePartType.new

	end

	def create
		@spare_part_type = SparePartType.new(spare_part_type_params)
	  if @spare_part_type.save
	    redirect_to :action => :index
	  else
	    render 'new'
	  end
	end

	def edit
		@spare_part_type = SparePartType.find(params[:id])
	end

	def update
		@spare_part_type = SparePartType.find(params[:id])
		@spare_part_type.update_attributes(spare_part_type_params)
		if @spare_part_type.save
	    redirect_to :action => :index
	  else
	    render 'edit'
	  end
	end

	def destroy
		@spare_part_type = SparePartType.find(params[:id])
		@spare_part_type.destroy
		redirect_to :action => :index
		flash.notice = "Sparepart type #{@spare_part_type.name} has been deleted"
	end

	private

  def spare_part_type_params
    params.require(:spare_part_type).permit(:name)
  end
end

another_vkh/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index

	end

	def new

	end

	def create

	end

	def edit

	end

	def update

	end

	def destroy

	end

	def change_password
    @user = current_user
  end
end

another_vkh/app/helpers/alert_helper.rb
module AlertHelper
end

another_vkh/app/helpers/application_helper.rb
module ApplicationHelper
	def section_active(action)
  	return (params[:controller] == action)? "active": ""
  end
end

another_vkh/app/helpers/car_histories_helper.rb
module CarHistoriesHelper
end

another_vkh/app/helpers/cars_helper.rb
module CarsHelper
end

another_vkh/app/helpers/home_helper.rb
module HomeHelper
end

another_vkh/app/helpers/spare_part_types_helper.rb
module SparePartTypesHelper
end

another_vkh/app/helpers/spare_parts_helper.rb
module SparePartsHelper
end

another_vkh/app/helpers/users_helper.rb
module UsersHelper
end

another_vkh/app/views/spare_part_types/_form.html.erb
<%= bootstrap_form_for(@spare_part_type, layout: :horizontal ,label_col: "col-sm-2", control_col: "col-sm-3") do |f| %>
  <%= f.text_field :name %>
  <%= f.form_group do %>
    <%= f.submit %>
  <% end %>
<% end %>

another_vkh/app/views/spare_part_types/edit.html.erb
<div id="wrapper">
	<h1 align="center">Edit Spare Part Type</h1>
	<%= render partial: 'spare_part_types/form' %>
</div>

another_vkh/app/views/spare_part_types/index.html.erb
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-8">
		<div class="nav">
		<%= form_tag spare_part_types_path, :method => 'get', :class => "form-inline" do %>
			<div class="navbar-nav navbar-left" style="margin-bottom: 10px;">
				<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search ..." %>
				<%= submit_tag "Search", :class => "btn btn-default" %>
			</div>
		<% end %>
	  <div class="navbar-nav navbar-right" style="margin-right: 0px;">
	  	<%= button_to "Add New", new_spare_part_type_path, :class => "btn btn-default", :method => "get" %>
	  </div>
  	</div>
  	<% if !@spare_part_types.empty? %>
		  <div class="panel panel-default">
				<table class="table table-striped table-hover">
					<th style="width: 20%"> ឈ្មោះ </th>
					<th style="width: 15%"> </th>

					<% @spare_part_types.each do |spare_part_type| %>
						<tr>
							<td> <%= spare_part_type.name %> </td>
							<td>
								<div>
									<span style = "margin-right: 10px;">
										<%= link_to "", edit_spare_part_type_path(spare_part_type), class: "glyphicon glyphicon-pencil" %>
									</span>
									<span style = "margin-right: 10px;">
										<%= link_to "", spare_part_type_path(spare_part_type), method: :delete, data: {confirm: "Are you sure want to delete this item?"}, class: "glyphicon glyphicon-trash" %>
									</span>
								</div>
							</td>
						</tr>
					<% end %>	
				</table>
			</div>
		<% end %>
		<div style="margin-top: -25px;">
			<% if !@spare_part_types.empty? %>
			<%= will_paginate @spare_part_types, renderer: BootstrapPagination::Rails %>
			<% end %>
		</div>
	</div>
</div>

another_vkh/app/views/spare_part_types/new.html.erb
<div id="wrapper">
  <div class="user-action">
    <h1 align="center">Register New Spare Part Type</h1>
    <%= render partial: 'spare_part_types/form' %>
  </div>
</div>