another_vkh/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'car_histories#index'
  resources :users do
    member do
      put 'update_password'
      get 'change_password'
    end
  end

  resources :cars do
    member do
      post 'add_more_detail'
    end
  end
  resources :spare_parts
  resources :spare_part_types
  resources :car_histories do
    member do
      post 'print'
    end
  end
  resources :car_repairing_quotes
  resources :alerts
  resources :historical_reports do 
    member do
      get 'quote'
    end
  end

end

another_vkh/app/models/car.rb
class Car < ActiveRecord::Base
	has_many :sell_reports
	has_many :car_histories
end

another_vkh/app/models/car_history.rb
class CarHistory < ActiveRecord::Base
	belongs_to :car
end

another_vkh/app/models/car_history_spare_part.rb
class CarHistorySparePart < ActiveRecord::Base
end

another_vkh/app/models/car_repairing_quote.rb
class CarRepairingQuote < ActiveRecord::Base
	belongs_to :car_repairing_quote_status
end

another_vkh/app/models/car_type.rb
class CarType < ActiveRecord::Base
end

another_vkh/app/models/sell_report.rb
class SellReport < ActiveRecord::Base
	belongs_to :car
	belongs_to :spare_part
end

another_vkh/app/models/spare_part.rb
class SparePart < ActiveRecord::Base
	belongs_to	:spare_part_type
	has_many :sell_reports
end

another_vkh/app/models/spare_part_type.rb
class SparePartType < ActiveRecord::Base
	has_many :spare_parts
end

another_vkh/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

another_vkh/app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
	def index
		@alerts = SparePart.where("amount_in_stock <= ?", 20)
	end
end

another_vkh/app/controllers/cars_controller.rb
class CarsController < ApplicationController

	def index
		@cars = Car.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@car = Car.new

	end

	def create
		@car = Car.new(car_params)
	  if @car.save
	    redirect_to :action => :index
	  else
	    render 'new'
	  end
	end

	def edit
		@car = Car.find(params[:id])
	end

	def update
		@car = Car.find(params[:id])
		@car.update_attributes(car_params)
		if @car.save
	    redirect_to :action => :index
	  else
	    render 'edit'
	  end
	end

	def destroy
		@car = Car.find(params[:id])
		@car.destroy
		redirect_to :action => :index
		flash.notice = "Car #{@car.plate_number} has been deleted"
	end

	private

  def car_params
    params.require(:car).permit(:plate_number, :name)
  end
	
end

another_vkh/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

another_vkh/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index

	end

	def new

	end

	def create

	end

	def edit

	end

	def update

	end

	def destroy

	end

	def change_password
    @user = current_user
  end
end

another_vkh/app/helpers/alert_helper.rb
module AlertHelper
end

another_vkh/app/helpers/application_helper.rb
module ApplicationHelper
	def section_active(action)
  	return (params[:controller] == action)? "active": ""
  end
end

another_vkh/app/helpers/car_histories_helper.rb
module CarHistoriesHelper
end

another_vkh/app/helpers/cars_helper.rb
module CarsHelper
end

another_vkh/app/helpers/home_helper.rb
module HomeHelper
end

another_vkh/app/helpers/spare_parts_helper.rb
module SparePartsHelper
end

another_vkh/app/helpers/users_helper.rb
module UsersHelper
end

another_vkh/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VkhProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<% if current_user%>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" style="margin-left: 90px;">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">VKH Management System</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=<%= section_active("car_histories")  %> style="padding-left: 20px; padding-right: 10px;"> <%= link_to raw('<i class="glyphicon glyphicon-usd" style="margin-right: 5px;"></i> Sell '), car_histories_path, :method => :get %> </li>
         <li class="nav-divider"></li>
        <li class=<%= section_active("historical_reports")  %> style="padding-left: 20px; padding-right: 10px;"> <%= link_to raw('<i class="glyphicon glyphicon-eye-open" style="margin-right: 5px;"></i>  History '), historical_reports_path, :method => :get %> </li>
        <li class="divider"></li>
        <li class="dropdown <%= section_active("spare_parts")  %>"> <%= link_to raw('<i class="glyphicon glyphicon-folder-open" style="margin-right: 5px;"></i> Spare Parts <span class="caret"></span>'), spare_parts_path, :method => :get, :'data-toggle' => 'dropdown' %>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Manage Type", spare_part_types_path %></li>
          </ul>
        </li>
        <li class=<%= section_active("cars")  %> style="padding-left: 20px; padding-right: 10px;"> <%= link_to raw('<i class="glyphicon glyphicon-folder-open" style="margin-right: 5px;"></i>  Car '), cars_path, :method => :get %> </li>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Manage Type</a></li>
          </ul>
        </li>
        <li class="divider-vertical"></li>
        <li class=<%= section_active("alerts")  %> style="padding-left: 10px; padding-right: 10px;"> <%= link_to raw('<i class="glyphicon glyphicon-bell" style="margin-right: 5px;"></i>  Alert <span class="badge">'"#{SparePart.where('amount_in_stock <= ?', 20).count}"'</span> '), alerts_path, :method => :get %> </li>
        <li class="divider-vertical"></li>
        <li><a class="glyphicon glyphicon-user" href="#"> User </a></li>
      </ul>
      <div class="btn-group pull-right">
				<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="icon-user"></i> <%= current_user.email || "UNKNOWN" %> <span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to " Profile", edit_user_path(current_user), :method => :get, :class => 'icon-user' %>
					<li class="divider"></li>
					<li><%= link_to " Change Password", change_password_user_path(current_user), :method => :get, :class => 'icon-cog' %>
					<li class="divider"></li>
					<li><%= link_to " Sign out", destroy_user_session_path, :method => :delete, :class => 'icon-share' %></li>
				</ul>
			</div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>


<%= yield %>

</body>
</html>